//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovoi.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Время_занятий
    {
        public string День { get; set; }
        public int Id_кабинета { get; set; }
        public int Id_расписания { get; set; }
    
        public virtual Кабинет Кабинет { get; set; }
        public virtual Расписание Расписание { get; set; }
    }
}
