//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyrsovoi.DB_
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Расписание()
        {
            this.Время_занятий = new HashSet<Время_занятий>();
        }
    
        public int Id_расписания { get; set; }
        public Nullable<int> Id_группы { get; set; }
        public Nullable<int> Id_преподавателя { get; set; }
        public Nullable<int> Id_предмета { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Время_занятий> Время_занятий { get; set; }
        public virtual Группа Группа { get; set; }
        public virtual Предмет Предмет { get; set; }
        public virtual Преподаватель Преподаватель { get; set; }
    }
}
